name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker
    env:
      tag_minor: "${{ github.repository }}:1.0"
      tag_patch: "${{ github.repository }}:1.0.${{ github.run_number }}"
      tag_latest: "${{ github.repository }}:latest"
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker pull ${tag_minor} || true
        docker build . --cache-from ${tag_minor} --tag ${tag_patch}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish Docker image
      run: |
        docker tag ${tag_patch} ${tag_minor}
        docker tag ${tag_patch} ${tag_latest}
        docker push ${{ github.repository }} --all-tags
